### ISSUE TITLE
an installer or a portable version

### ISSUE THREAD

**Issue by aethersphere** [xzeldon/razer-battery-report#1]
Could u please make an installer or upload already built portable version of this program? As a normie who's not familiar with building programs this would be really convenient.

**Comment by xzeldon** [comment]
Here it is: 
[razer-battery-report.zip](https://github.com/user-attachments/files/18041004/razer-battery-report.zip) v0.2.3 (commit: `f5349a56a5852aaa2b2337c86181018e0ce39bda`)

**SHA-256 zipped**: `222f96aaece8a84604ad0bed7462a8132ce2eabe2ac860fad019c24acfd0ca62`
**SHA-256 unzipped**: `a76dc2f7b2300ac26f75ecbd2d122126e35a61c9f9dbf85433e91ada87db0532`
**VirusTotal zipped**: https://www.virustotal.com/gui/url/794bde939493608d5f149710fc5b24bb243b2a24dcf3ad7900e5fc0baeb9fe13

Thank you for interest in the project!

The primary reason I haven’t provided pre-built binaries is that the program is still somewhat incomplete, and I’m not fully satisfied with its current state. I’d prefer not to distribute it widely in this form. **There are known threading sync issues that can cause the tray applet’s interface to appear frozen.** (Mainly in the first 5-10 seconds after start-up).

Unfortunately, I’ve had very little time recently to work on side projects like this one. 

Please keep in mind that this version is provided “as is” and may still have some rough edges.

**Comment by aethersphere** [comment]
I see, apparently it doesn't show battery percentage of my DeathAdder v3 Hyperspeed. I was just looking for a simple lightweight program to check mouse battery % instead of using bloated razer synapse. Thanks for the effort anyways :)

**Comment by xzeldon** [comment]
> I see, apparently it doesn't show battery percentage of my DeathAdder v3 Hyperspeed. I was just looking for a simple lightweight program to check mouse battery % instead of using bloated razer synapse. Thanks for the effort anyways :)

That's because the **V3 HyperSpeed** isn't actually the **V3 Pro**. I've added support for V3 HyperSpeed, supposedly everything should work. If you don't mind, you can check it out: 

[razer-battery-report.zip](https://github.com/user-attachments/files/18053294/razer-battery-report.zip) v0.2.3
**SHA-256 zipped**: `39811b19e87c8be3cd2d2f2736e29e844b603f5ef7541ff29ac1e1755dcfbebb`
**SHA-256 unzipped**: `2a6e7ef87cbadfb609ad44363e9b079da54f3612100c943aa4199d4c9fae5c5c`
**VirusTotal zipped**: https://www.virustotal.com/gui/url/e2f823b4de1c4aed6120bcb4c96d955ceb904dccc7a23f50a9858c28d255eb40

**Comment by aethersphere** [comment]
Works now, thanks!
